name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
          echo ${{ secrets.ALIYUN_DOCKER_PASSWORD }} | docker login ${{ vars.REGISTRY_MIRROR }} --username ${{ secrets.ALIYUN_DOCKER_USERNAME }} --password-stdin

          docker image build -t ${{ vars.APP_NAME }}:latest .
          docker tag ${{ vars.APP_NAME }} ${{ vars.REGISTRY_MIRROR }}/${{ vars.REGISTRY_NAMESPACE }}/${{ vars.APP_NAME }}:latest
          docker push ${{ vars.REGISTRY_MIRROR }}/${{ vars.REGISTRY_NAMESPACE }}/${{ vars.APP_NAME }}:latest
          docker logout

          echo "app name ${{ vars.REGISTRY_MIRROR }}"

    - name: ssh remote deploy
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd /
          echo -e "1.docker login start==>"
          echo ${{ secrets.ALIYUN_DOCKER_PASSWORD }} | docker login ${{ vars.REGISTRY_MIRROR }} --username ${{ secrets.ALIYUN_DOCKER_USERNAME }} --password-stdin

          echo -e "2.docker stop myblog container==>"
          docker container stop ${{ vars.APP_NAME }}

          echo -e "3.docker conatainer rm==>"
          docker container rm ${{ vars.APP_NAME }}

          echo -e "4.docker image rm==>"
          docker image rm ${{ vars.REGISTRY_MIRROR }}/${{ vars.REGISTRY_NAMESPACE }}/${{ vars.APP_NAME }}:latest

          echo -e "5.docker pull==>"
          docker pull ${{ vars.REGISTRY_MIRROR }}/${{ vars.REGISTRY_NAMESPACE }}/${{ vars.APP_NAME }}:latest

          echo -e "6.docker container create and start==>"
          docker container run -d -p 3000:3000 --name ${{ vars.APP_NAME }} ${{ vars.REGISTRY_MIRROR }}/${{ vars.REGISTRY_NAMESPACE }}/${{ vars.APP_NAME }}:latest

          echo -e "7.docker logout==>"
          docker logout
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USER }}
        pass: ${{ secrets.PASSWORD }}

